services:
  language-detection:
    image: mcr.microsoft.com/azure-cognitive-services/speechservices/language-detection:latest
    environment:
      Eula: accept
      Billing: ${SPEECH_BILLING_URL}
      ApiKey: ${SPEECH_API_KEY}

  speech-to-text:
    image: mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:latest
    ports:
      - 5000:5000
    environment:
      Eula: accept
      Billing: ${SPEECH_BILLING_URL}
      ApiKey: ${SPEECH_API_KEY}
      Logging__Console__LogLevel__Default: Information 

  sending:
      build: .
      volumes:
        - .:/app # Mount local sending folder to /app in the container
      command: python /app/sending.py  # Run sending.py when the container starts
      environment:
        - SPEECH_KEY=${SPEECH_API_KEY}
        - SPEECH_REGION=${SPEECH_REGION}
